[package]
name = "rs-switcher"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.12"
uinput = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
log = "0.4"
env_logger = "0.10"
glob = "0.3"
