[package]
name = "rs-switcher"
version = "0.1.0"
edition = "2024"

[dependencies]
glob = "0.3.3"
env_logger = "0.11.8"
log = "0.4.29"
toml = "0.9.11"
serde = { version = "1.0.228", features = ["derive"] }
uinput = "0.1.3"
evdev = "0.13.2"

