trigger_key = "KEY_PAUSE"
layout_switch_combo = ["KEY_LEFTMETA", "KEY_SPACE"]
ignored_keywords = ["mouse", "touchpad", "video", "button", "headset"]
buffer_size = 100
retry_delay_ms = 1000
device_timeout_ms = 60000
device_path = ""
